l_japanese:

 bbc_worshipper_soothing_touch: "穏やかな 触覚" # AI Tags
 bbc_worshipper_soothing_touch_desc: "力強い男性の不安な欲望を 熟練した舌で鎮めるために 彼女は親密な奉仕を通して 忠誠の絆を 築き上げ [control|E] 彼らに負けて." # AI Tags
 bbc_worshipper_golden_hour: "黄金時間" # AI Tags
 bbc_worshipper_golden_hour_desc: "秘密の潜在能力を解き放つことができると 彼女は信じています [bno_black|E] 人々が私的な部屋で,より大きな野心を燃やし, [development|E] 共有の恋愛を通して." # AI Tags